// This file is autogenerated. Changes will be overwritten.
#include "AEPA3XL4CW/moc_coordinatesystem.cpp"
#include "AEPA3XL4CW/moc_cylinder3d.cpp"
#include "AEPA3XL4CW/moc_joint.cpp"
#include "AEPA3XL4CW/moc_robot.cpp"
